# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testerwork',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('worktime', models.CharField(max_length=100)),
                ('avgtime', models.CharField(max_length=100)),
                ('txtime', models.CharField(max_length=100)),
                ('csxl', models.CharField(max_length=100)),
            ],
        ),
    ]
